<?php

$observers = [
    [
        'eventname'=>'\core\event\course_module_created',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_module_deleted',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_module_updated',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_module_completion_updated',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\message_sent',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\message_viewed',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\message_deleted',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_created',
        'callback'=>'local_collector_alert_bun_observer::user_created',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_deleted',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_updated',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_enrolment_created',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_enrolment_deleted',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\user_enrolment_updated',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_created',
        'callback'=>'local_collector_alert_bun_observer::course_created',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_deleted',
        'callback'=>'local_collector_alert_bun_observer::course_delete',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
    [
        'eventname'=>'\core\event\course_updated',
        'callback'=>'',
        'includefile'=>null,
        'internal'=>true,
        'priority'=>9999
    ],
];